{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gohello.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
spec:
  host: {{ .Values.ingress.host }}
  wildcardPolicy: {{ .Values.ingress.wildcardPolicy }}
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ required "A valid .Values.service.name entry required!" .Values.service.name }}
    weight: {{ .Values.service.weight }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect