apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: go-hello-route
spec:
  host: {{ .Values.ingress.host }}
  wildcardPolicy: {{ .Values.ingress.wildcardPolicy }}
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: {{ .Values.service.weight }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect